version: '3.8'

services:
  oikura-user-web:
    container_name: 'oikura.user.web'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '50011:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - oikura-user-php
    #  - tw-mysql
    networks:
      - oikura-dev-network
      
  oikura-user-php:
    container_name: 'oikura.user.php'
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    #command: php artisan serve --port 3000
    # viteでフロントエンドをビルドする場合
    # ports:
    #   - '5173:5173'
    networks:
      - oikura-dev-network

  util-npm:
    image: node:20.10.0
    working_dir: /var/www/html
    #entrypoint: ['npm']
    volumes:
      - ./src:/var/www/html

networks:
  oikura-dev-network:
    external: true